# Generated by Django 3.2 on 2022-12-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0017_entry_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
